### ISSUE TITLE
Hacer tests del controlador

### ISSUE THREAD

**Issue by victorcastanogutierrez** [Arquisoft/voters_4a#6]
Hacer métodos test en la clase VoterRepositoryTest que prueben el acceso por método POST a la aplicación.

**Comment by victorcastanogutierrez** [comment]
Ya hice la clase de test para el controlador y metí dos test básicos. Hay que ampliarlos y crear nuevos

**Comment by Corobo** [comment]
Hice dos métodos test para el cambio de contraseña.

**Comment by victorcastanogutierrez** [comment]
Nuevo test controlando password incorrecta
